services:
  pencilbeamworker:
    image: nexus.sibedge.com/spl-docker/tpl_worker/v1/1.0.0:89da07
    container_name: pencilbeamworker
    restart: unless-stopped
    volumes:
      - ./tps_data/storage:/data/storage
    environment:
      - CommonSettings__MessageBrokerSettings__Host=mq
      - CommonSettings__MessageBrokerSettings__Port=5672
      - CommonSettings__MessageBrokerSettings__UserName=admin
      - CommonSettings__MessageBrokerSettings__Password=byJKQ7%OG3l3
    env_file: ./backend/.env
    depends_on:
      mq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'