
services:
  orthanc:
    image: jodogne/orthanc-plugins
    volumes:
      - ./orthanc_data/:/run/secrets/OrthancStorage/
    restart: always
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=orthanc
secrets:
  orthanc.json:
    file: orthanc.json
